function SARIMA_Huaxian_310313T = modelTimeSeries310313T(Huaxian)
%%Time Series Modeling Using the Econometric Modeler
% This code recreates the estimated model produced in the Econometric Modeler app. Use the code below to estimate the same model, or estimate a model with the same parameters on a new set of data.
%
%Input: A numeric matrix with the same number of columns as the data imported into the app (Huaxian)
%
%Output: The model containing estimated parameters (SARIMA_Huaxian_310313T)
%
%Auto-generated by MATLAB Version 9.7 (R2019b) and Econometrics Toolbox Version 5.3 on 05-May-2020 14:33:33
Huaxian1 = Huaxian(:,1);

%% Seasonal ARIMA Model
% Estimate a SARIMA Model of Huaxian1
SARIMA_Huaxian_310313T = arima('Constant',NaN,'ARLags',1:3,'D',1,'MALags',[],'SARLags',[12,24,36],'Seasonality',12,'SMALags',[12,24,36],'Distribution','t');
SARIMA_Huaxian_310313T = estimate(SARIMA_Huaxian_310313T,Huaxian1,'Display','off');
end